### ISSUE TITLE
Old version import function

### ISSUE THREAD

**Issue by MrAlexWeber** [paulgibbs/achievements#93]
I want to help write this feature, because I need to use it!
Here's my stab at an outline:
- Query the DB for the old ones from wp_achievements
- for each achievement_row, insert a new custom post in WP
  Any suggestions on this second step, particularly the new post creation?

**Comment by paulgibbs** [comment]
Ideally this will be modelled on how the bbPress converters work:

https://bbpress.trac.wordpress.org/browser/trunk/includes/admin/converters
https://bbpress.trac.wordpress.org/browser/trunk/includes/admin/converter.php

@johnjamesjacoby wrote a lot of code that prevents timeouts due to large queries and doing the import in batch, so I think we should just borrow BBP_Converter, get it in, then build an importer class.

I need to go look at Achievements 2 to get the DB structure and user meta fields etc I was using. I'll try to put some notes together this weekend and post them here, so we have something easy to refer to.

**Comment by paulgibbs** [comment]
Haven't got to this in a half-year, so closing.
